jobs:
  create-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Creates the dependencies required for the python project to run
        run: pip download -r requirements.txt -d deps/ 
      - name: Move to the directory with dependencies
        run: cd deps/ && unzip "*.whl" -d ../libs
      - name: Package all the dependencies
        run: zip -r formula-assets.zip libs
      - name: Delete the existing release
        run: gh release delete formula-assets --yes
      - name: create a release asset from the formula-assets
        run: gh release create formula-assets formula-assets.zip
    env: 
      GH_TOKEN: ${{github.token}}
    permissions:
      contents: write
"on": "push"