jobs:
  create-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Creates the dependencies required for the python project to run
        run: pip download -r requirements.txt -d deps/ 
      - name: Move to the directory with dependencies
        run: cd deps/ 
      - name: List  all dependencies for comfort
"on": "push"